image: registry.gitlab.com/pages/hugo:0.32.3

test:
  script:
  - hugo --buildFuture
  except:
  - master

pages:
  stage: deploy
  script:
    - hugo --buildFuture
  artifacts:
    paths:
    - public
  only:
  - master