image: registry.gitlab.com/pages/hugo:0.32.3

test:
  script:
  - hugo --buildFuture
  except:
  - master

pages:
  script:
    - hugo --buildFuture
    - find public -type f regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -execdir gzip -f --keep {} \;
  artifacts:
    paths:
    - public
  only:
  - master
