image: registry.gitlab.com/pages/hugo:0.32.3

test:
  script:
  - hugo --buildFuture
  except:
  - master

pages:
  stage: deploy
  script:
    - hugo --buildFuture
  artifacts:
    paths:
    - public
  only:
  - master

triggerWebhook:
  stage: deploy
  script:
    - eval $POST_BUILD_WEBHOOK
  when: on_success
  variables:
      POST_BUILD_WEBHOOK: "true"