image: registry.gitlab.com/pages/hugo:0.58.3

test:
  script:
  - hugo --buildFuture
  except:
  - master

pages:
  stage: deploy
  script:
    - hugo --buildFuture
  artifacts:
    paths:
    - public
  only:
  - master

  Scheduled deploy to Netlify:
   image: alpine
   only:
     - schedules
   script:
     - apk add curl
     - curl -X POST -d {} https://api.netlify.com/build_hooks/$NETLIFY_HOOK
