baseurl = "https://mainlandbigband.gitlab.io"
languageCode = "en-nz"
title = "Mainland Big Band"
theme = "mbbred"

sectionPagesMenu = "main"

[[menu.main]]
    name = "About"
    url  = "/"
    weight = 1
