baseurl = "https://mainlandbigband.co.nz"
languageCode = "en-nz"
title = "Mainland Big Band"
theme = "mbbred"

sectionPagesMenu = "main"

[[menu.main]]
    name = "About"
    url  = "/"
    weight = 1

[outputs]
home = [ "HTML", "RSS", "HEADERS" ]
    
[mediaTypes]
[mediaTypes."text/netlify"]
suffix = ""
delimiter = ""

[outputFormats]
[outputFormats.HEADERS]
mediatype = "text/netlify"
baseName = "_headers"
isPlainText = true
notAlternative = true